version: "3.7"
services:
  mongo:
    image: mongo:4.4.10
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: BovegroDB
      MONGO_INITDB_ROOT_PASSWORD: BovegroDB123
    ports:
      - "0.0.0.0:27017:27017"
    networks:
      - MONGO
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/mongoDB
      - type: volume
        source: MONGO_CONFIG
        target: /data/mongoConfig
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: BovegroDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: BovegroDB123
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_BASICAUTH_USERNAME: adminBovegro
      ME_CONFIG_BASICAUTH_PASSWORD: admin123Bovegro
    ports:
      - "0.0.0.0:27018:8081"
    restart: always
    networks:
      - MONGO
    depends_on:
      - mongo

networks:
  MONGO:
    name: MONGO

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
